name: YT Summarizer
on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours (00:00, 06:00, 12:00, 18:00 UTC)
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install Deps
        run: pip install requests google-generativeai mailjet_rest pytz
      - name: Run
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          MAILJET_API_KEY: ${{ secrets.MAILJET_API_KEY }}
          MAILJET_SECRET_KEY: ${{ secrets.MAILJET_SECRET_KEY }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        run: python script.py
